# colors + shapes
#preload = ~/.config/hypr/wallpapers/abstract/wallpaper1.jpg
#preload = ~/.config/hypr/wallpapers/abstract/wallpaper2.jpg
#preload = ~/.config/hypr/wallpapers/abstract/wallpaper3.jpg
# tokyo
#preload = ~/.config/hypr/wallpapers/tokyo/left.jpg
#preload = ~/.config/hypr/wallpapers/tokyo/center.jpg
#preload = ~/.config/hypr/wallpapers/tokyo/right.jpg
# abandoned
preload = ~/.config/hypr/wallpapers/urban/main_rig/31339622218_a176ab8306_k.jpg
preload = ~/.config/hypr/wallpapers/urban/main_rig/49523824211_574e646394_4k.jpg
preload = ~/.config/hypr/wallpapers/urban/main_rig/50208825893_dcec97953f_4k.jpg
# left
wallpaper {
  monitor = DP-2
  path = ~/.config/hypr/wallpapers/urban/main_rig/50208825893_dcec97953f_4k.jpg
}

# center
wallpaper {
  monitor = DP-1
  path = ~/.config/hypr/wallpapers/urban/main_rig/49523824211_574e646394_4k.jpg
}

# right
wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/wallpapers/urban/main_rig/31339622218_a176ab8306_k.jpg
}
